default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_app_development

test:
  <<: *default
  database: api_app_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: api_app_production_cable
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: api_app_production_cache
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: api_app_production_queue