services:
  - type: web
    name: rails-api
    env: ruby
    buildCommand: bundle install && bundle exec rake db:migrate db:cable_migrate db:cache_migrate db:queue_migrate
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_api_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: rails_api_db
    databaseName: api_app_production